### PR TITLE
FIX: Track deletions correctly

### LINKED ISSUE #33: Deletions not snapshotted
Deletions aren't being snapshotted, because the record isn't found by the event handler and so snapshot creation is skipped.

### PR DESCRIPTION
**Pull request by sminnee**
Because $obj->ID is set to 0 on a deleted record, this broke the existing
snapshot creation.

Relies on https://github.com/silverstripe/silverstripe-versioned/pull/280,
without which deletions are logged as another creation.

Fixes #33

### CODE REVIEW

File: src/Handler/Form/Handler.php [hunk 1]
```diff
@@ -74,13 +74,18 @@ protected function getRecordFromContext(EventContextInterface $context): ?DataOb
         $form = $context->get('form');
 
         $record = $form->getRecord();
+
         if (!$record) {
             return null;
         }
-        if ($record->hasExtension(Versioned::class) && $record->isArchived()) {
+
+        $refetched = DataObject::get_by_id($record->baseClass(), $record->ID);
```
Comment (sminnee) [inline src/Handler/Form/Handler.php:82]: It's not clear to me why we _need_ to re-fetch the record here, and can't simply return the existing record in all cases.

**Comment by sminnee** [comment]
@unclecheese would be good to get this reviewed if you have chance.

**Comment by unclecheese** [comment]
LGTM
